---
name: Build and Push Python Image to GCP
on:
    push:
        branches: [ main ]

env:
    IMAGE_NAME: lesson-087
    PROJECT_ID: eks-202411-441114
    GAR_LOCATION: us-west2-docker.pkg.dev/eks-202411-441114/images/
    GIT_TAB: v0.1.0

jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

        - name: "Setup Cloud SDK"
          uses: 'google-github-actions/setup-gcloud@v1'

        - name: Configure Docker Auth
          run: |
            gcloud auth configure-docker us-west2-docker.pkg.dev  --quiet
        
        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME:latest .

        - name: Push Docker Image to Artifact Registry
          run: |
            docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
            docker push ${{ env.GAR_LOCATION }}