---
name: Build and Push Python Image to GCP
on:
    push:
        branches: [ main ]

env:
    IMAGE_NAME: lesson-087
    PROJECT_ID: eks-202411-441114
    GAR_LOCATION: us-west2-docker.pkg.dev/eks-202411-441114/images/
    GIT_TAB: v0.1.0
    WORKING_DIR: billyleunghk
    DOCKER_LOC: lesson-087
    WORKLOAD_PROVIDER_ID: projects/786081891380/locations/global/workloadIdentityPools/githubactions-pool/providers/wkld-provider
    SERVICE_ACCOUNT_ID: githubactions-wkid@eks-202411-441114.iam.gserviceaccount.com
jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest      
        
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            token_format: access_token
            workload_identity_provider: ${{ env.WORKLOAD_PROVIDER_ID }}
            service_account: ${{ env.SERVICE_ACCOUNT_ID }}
            access_token_lifetime: 300s

        - name: Login to Artifact Registry
          uses: docker/login-action@v1
          with:
            registry: us-west2-docker.pkg.dev
            username: oauth2accesstoken
            password: ${{ steps.auth.outputs.access_token }}
        
        - name: Build Docker Image
          run: docker build -t ${{ env.IMAGE_NAME }}:latest .

        - id: docker-push-tagged
          name: Tag Docker image and push to Google Artifact Registry
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: |
               ${{ env.IMAGE_NAME }}:${{ env.GIT_TAB }}
               ${{ env.IMAGE_NAME }}:latest